#!/bin/bash
# Позаимствовано
# https://github.com/arkenfox/user.js/blob/master/user.js
# https://github.com/farag2/Mozilla-Firefox/blob/master/user.js
# https://github.com/gjpin/arch-linux/blob/main/setup.sh

sudo -u $(whoami) timeout 5 firefox --headless
for FIREFOX_PROFILE_PATH in $HOME/.mozilla/firefox/*.default*
do
# Создание папки с расширениями
mkdir -p ${FIREFOX_PROFILE_PATH}/extensions

# Импорт темы
curl https://addons.mozilla.org/firefox/downloads/file/3913593/matte_black_red-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{a7589411-c5f6-41cf-8bdc-f66527d9d930}.xpi

# Импорт расширений
# Violentmonkey
curl https://addons.mozilla.org/firefox/downloads/file/4050539/violentmonkey-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{aecec67f-0d10-4fa7-b7c7-609a2db280cf}.xpi
# TWP - Translate Web Pages
curl https://addons.mozilla.org/firefox/downloads/file/4011167/traduzir_paginas_web-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{036a55b4-5e72-4d05-a06c-cba2dfcc134a}.xpi
# UBlock Origin
curl https://addons.mozilla.org/firefox/downloads/file/4003969/ublock_origin-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/uBlock0@raymondhill.net.xpi
# Auto Tab Discard (Усыпление вкладок)
curl https://addons.mozilla.org/firefox/downloads/file/4045009/auto_tab_discard-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{c2c003ee-bd69-42a2-b0e9-6f34222cb046}.xpi
# TSE - Torrents Search Engine
curl https://addons.mozilla.org/firefox/downloads/file/3983730/tse_torrents_search_engine-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/tse@example.com.xpi
# 7TV (Twitch)
curl https://addons.mozilla.org/firefox/downloads/file/3988775/7tv-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{7ef0f00c-2ebe-4626-8ed7-3185847fcfad}.xpi
# ff2mpv
curl https://addons.mozilla.org/firefox/downloads/file/3898765/ff2mpv-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/ff2mpv@yossarian.net.xpi
# Enchanced h264ify
curl https://addons.mozilla.org/firefox/downloads/file/3009842/enhanced_h264ify-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{9a41dee2-b924-4161-a971-7fb35c053a4a}.xpi
# Обход блокировок Рунета
curl https://addons.mozilla.org/firefox/downloads/file/3865240/2668061-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{290ce447-2abb-4d96-8384-7256dd4a1c43}.xpi
# Browsec VPN (Временный vpn)
curl https://addons.mozilla.org/firefox/downloads/file/4043870/browsec-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/browsec@browsec.com.xpi
# Dark Reader
curl https://addons.mozilla.org/firefox/downloads/file/4021899/darkreader-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/addon@darkreader.org.xpi
# Return Youtube Dislikes
curl https://addons.mozilla.org/firefox/downloads/file/4005382/return_youtube_dislikes-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{762f9885-5a13-4abd-9c77-433dcd38b8fd}.xpi
# S3 Translation
curl https://addons.mozilla.org/firefox/downloads/file/3999550/s3_translator-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/s3@translator.xpi
# Keepassxc Browser
curl https://addons.mozilla.org/firefox/downloads/file/4023682/keepassxc_browser-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/keepassxc-browser@keepassxc.org.xpi
# SponsorBlock
curl https://addons.mozilla.org/firefox/downloads/file/4026759/sponsorblock-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/sponsorBlocker@ajay.app.xpi
# SteamDB
curl https://addons.mozilla.org/firefox/downloads/file/4026911/steam_database-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/firefox-extension@steamdb.info.xpi
# Cute Save Button
curl https://addons.mozilla.org/firefox/downloads/file/3900368/cute_save_button-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/ochecuteextension@plaza.ink.xpi
# DownloadThemAll!
curl https://addons.mozilla.org/firefox/downloads/file/3983650/downthemall-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{DDC359D1-844A-42a7-9AA1-88A850A938A8}.xpi
# Cookie AutoDelete
curl https://addons.mozilla.org/firefox/downloads/file/3971429/cookie_autodelete-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/CookieAutoDelete@kennydo.com.xpi
# Dollchan Extension Tools
curl https://addons.mozilla.org/firefox/downloads/file/4027739/dollchan_extension-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/dollchan_extension@dscript.me.xpi
# Proxy SwitchyOmega
curl https://addons.mozilla.org/firefox/downloads/file/1056777/switchyomega-latest.xpi
# cookies-txt-one-click
curl https://addons.mozilla.org/firefox/downloads/file/3452835/cookies_txt_one_click-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{520a19d3-2d3c-47ee-ba15-cd66aae65db2}.xpi
# Bookmark Dupes
curl https://addons.mozilla.org/firefox/downloads/file/3988430/bookmark_dupes-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/bookmarkdupes@martin-vaeth.org.xpi
# Fixed Zoom
curl https://addons.mozilla.org/firefox/downloads/file/1705492/fixed_zoom-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{a655a6b2-69a5-40de-a3b8-3f7f200c95a7}.xpi
# Enforce Browser Fonts - полезно особенно для Linuxv
curl https://addons.mozilla.org/firefox/downloads/file/3782841/enforce_browser_fonts-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/{83e08b00-32de-44e7-97bb-1bab84d1350f}.xpi
# Don't "Accept" image/webp
curl https://addons.mozilla.org/firefox/downloads/file/3941342/dont_accept_webp-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/dont-accept-webp@jeffersonscher.com.xpi

# curl https://addons.mozilla.org/firefox/downloads/file/3998783/floccus-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/floccus@handmadeideas.org.xpi
# curl https://addons.mozilla.org/firefox/downloads/file/3932862/multi_account_containers-latest.xpi -o ${FIREFOX_PROFILE_PATH}/extensions/@testpilot-containers.xpi


# Импорт пользовательских конфигураций
tee ${FIREFOX_PROFILE_PATH}/user.js << EOF
// --- HW Accel и включение FFMPEG VA-API
// https://wiki.archlinux.org/title/Firefox#Hardware_video_acceleration
user_pref("media.ffmpeg.vaapi.enabled", true);
user_pref("gfx.webrender.all", true);

// Отключает строку заголовка
user_pref("browser.tabs.inTitlebar", 1);

// Отключает функцию View
user_pref("browser.tabs.firefox-view", false);

// Отключает кнопку  списка вкладок
 // user_pref("browser.tabs.tabmanager.enabled", false);

// Отключает проверку браузера по умолчанию
user_pref("browser.shell.checkDefaultBrowser", false);

// Никаких всплывающих (Popup) окон вообще! (Очень полезно)
user_pref("browser.link.open_newwindow.restriction", 0);

// Включает скролл на среднюю кнопку мыши
user_pref("general.autoScroll", true);

// --- Оптимизация
// Уменьшение потребление памяти
user_pref("dom.ipc.processCount", -1); // -1 is equivalent to 'no limit', change accordingly
user_pref("dom.ipc.processCount.webIsolated", 1); // сколько процессов будет выделено для каждого сайта
user_pref("dom.suspend_inactive.enabled", true); // приостановить неактивные вкладки
// Сокращение операций чтения/записи Firefox
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.memory.enable", true);
user_pref("browser.cache.memory.capacity", 1048576);
user_pref("browser.sessionstore.interval", 15000000);

// --- STARTUP / HOME
// Отключает приветствие
user_pref("browser.startup.homepage_override.mstone", "ignore");
// Устанавливает стартовую страницу
// 0=пусто, 1=главная, 2=последняя посещенная страница, 3=возобновить предыдущую сесси ю
user_pref("browser.startup.page", 3);
// Домашняя страница и новые окна
user_pref("browser.startup.homepage", "about:blank");
// Новые вкладки
user_pref("browser.newtabpage.enabled", false);
// Отключает спонсируемый контент в Firefox (Ярлыки)
user_pref("browser.newtabpage.activity-stream.showSponsored", false); // Pocket > Sponsored Stories
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false); // Sponsored shortcuts
// Очищать топ-сайты по умолчанию
user_pref("browser.newtabpage.activity-stream.default.sites", "");
user_pref("browser.topsites.contile.enabled", false);
user_pref("browser.topsites.useRemoteSetting", false);
// Всегда отображать панель закладок
user_pref("browser.toolbars.bookmarks.visibility", "always");
// Открывать N-ое кол-во закладок из папки не закрывая список
user_pref("browser.bookmarks.openInTabClosesMenu", false);
user_pref("browser.tabs.loadBookmarksInBackground", true);
// Отключает рекомендацию расширений
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);

// --- Отключает WebRTC
   // user_pref("media.peerconnection.enabled", false);

// --- Privacy & Security & Отключение телеметрии
// Enable Firefox Tracking Protection
user_pref("browser.contentblocking.category", "strict");
// Отключает менеджер логинов и паролей
user_pref("signon.rememberSignons", false);
user_pref("signon.autofillForms", false);
user_pref("signon.generation.enabled", false);
// Отключает панель рекомендаций в about:addon (используется Google Analytics)
user_pref("extensions.getAddons.showPane", false); // [HIDDEN PREF]
// Отключает рекомендации в панелях расширений и тем about:addons
user_pref("extensions.htmlaboutaddons.recommendations.enabled", false);
// Отключает персонализированные рекомендации по расширениям в about:addons и AMO
user_pref("browser.discovery.enabled", false);
// Отключает Сбор и использование данных Firefox
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");
// Включает Только-HTTPS режим
user_pref("dom.security.https_only_mode", true);
// Disable Location-Aware Browsing (geolocation)
user_pref("geo.enabled", false);
// Отключание отправки новых данных
user_pref("datareporting.policy.dataSubmissionEnabled", false);
// Отключение Телеметрии
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.server", "data:,");
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
// disable Telemetry Coverage
user_pref("toolkit.telemetry.coverage.opt-out", true); // [HIDDEN PREF]
user_pref("toolkit.coverage.opt-out", true); // [HIDDEN PREF]
user_pref("toolkit.coverage.endpoint.base", "");
// Отключает отправку дополнительной аналитики на веб-серверы
user_pref("beacon.enabled", false);
// disable PingCentre telemetry (used in several System Add-ons)
user_pref("browser.ping-centre.telemetry", false);
// disable Firefox Home (Activity Stream) telemetry
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry", false);
// Отключение отправки о вылетах браузера
user_pref("breakpad.reportURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);

// --- Разное
// Не отображать строку меню при нажатии Alt
user_pref("ui.key.menuAccessKeyFocuses", false);
// Отключает Mozilla аккаунт & Sync
user_pref("identity.fxaccounts.enabled", false);
// Отключает Pocket
user_pref("browser.pocket.enabled", false);
user_pref("extensions.pocket.enabled", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories",	false);
// Новые запросы на отправку уведомлений
// 0=Спрашивать, 1=Всегда отправлять, 2=Блокировать
user_pref("permissions.default.desktop-notification", 2);

// Автовоспроизведение видео
// 0=Разрешить всё, 1=Блочить незаглушенные медиа (по умолчанию), 5=Блочить всё
user_pref("media.autoplay.default", 5);
// Если некоторые сайты ДЕЙСТВИТЕЛЬНО нуждаются в автовоспроизведении...
// 0=sticky (default), 1=transient, 2=user
user_pref("media.autoplay.blocking_policy", 2);

// Disable Gnome Shell Integration NPAPI plugin
user_pref("plugin.state.libgnome-shell-browser-plugin", 0);

// Установить URL автоматической настройки прокси
user_pref("network.proxy.autoconfig_url", "https://antizapret.prostovpn.org/proxy.pac");
// Тип прокси
// 0=Прямое соединение, без прокси, 1=Ручная настрока прокси, 2=PAC (Proxy Auto-Configuration),
// 4=Авто обнаружение настроек прокси, 5=Использовать системные настроки прокси (Default)
user_pref("network.proxy.type", 2);
EOF

done
